# Minecart 2.3.1
# Plugin Feito Pela SnowDev
# Site https://minecart.com.br

Minecart:
  ShopKey: 'minecart_shop_key_api'
  ShopServer: 'minecart_server_name'

config:
  force_clean_inventry: true
  prefix: '&b[Minecart] '